imagesift: alloc.cpp error.cpp kdtree.cpp sift.cpp xform.cpp cv.cpp test.cpp imgfeatures.cpp minpq.cpp smooth.cpp utils.cpp
	g++ -w alloc.cpp error.cpp kdtree.cpp sift.cpp xform.cpp cv.cpp test.cpp imgfeatures.cpp minpq.cpp smooth.cpp utils.cpp -o similarimage -ljpeg -lm

